<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KebabSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kebabs = [
            [
                'name' => 'Dino Kebab',
                'logo' => 'dinokebablogo.png',
                'address' => 'Jaworzyńska 41, 59-220 Legnica',
                'latitude' => 51.20063341864202,
                'longitude' => 16.159551157050185,
                'year_opened' => 2021,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:00-22:00',
                        'tuesday' => '11:00-22:00',
                        'wednesday' => '11:00-22:00',
                        'thursday' => '11:00-22:00',
                        'friday' => '11:00-22:00',
                        'saturday' => '12:00-22:00',
                        'sunday' => '12:00-22:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['garlic', 'spicy', 'ketchup', 'mixed'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'Pyszne.pl', 'website', 'GLOVO'],
                ],
            ],
            [
                'name' => 'BAFRA Kebab',
                'logo' => 'BAFRAKebablogo.png',
                'address' => 'Gwiezdna 4, 59-220 Legnica',
                'latitude' => 51.20845974392724,
                'longitude' => 16.18173443766115,
                'year_opened' => 2024,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-21:00',
                        'tuesday' => '10:00-21:00',
                        'wednesday' => '10:00-21:00',
                        'thursday' => '10:00-21:00',
                        'friday' => '10:00-21:00',
                        'saturday' => '10:00-21:00',
                        'sunday' => '11:00-20:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => true,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats'],
                ],
            ],
            [
                'name' => 'BAFRA Kebab',
                'logo' => 'BAFRAKebablogo.png',
                'address' => 'Złotoryjska 170, 59-220 Legnica',
                'latitude' => 51.193006027448234,
                'longitude' => 16.128925187136065,
                'year_opened' => 2024,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-21:00',
                        'tuesday' => '10:00-21:00',
                        'wednesday' => '10:00-21:00',
                        'thursday' => '10:00-21:00',
                        'friday' => '10:00-21:00',
                        'saturday' => '10:00-21:00',
                        'sunday' => '11:00-20:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => true,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats'],
                ],
            ],
            [
                'name' => 'Zahir Kebab',
                'logo' => 'ZahirKebab.png',
                'address' => 'Jaworzyńska 8, 52-220 Legnica',
                'latitude' => 51.20424220227041,
                'longitude' => 16.16021083492278,
                'year_opened' => 2021,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-23:00',
                        'tuesday' => '10:00-23:00',
                        'wednesday' => '10:00-23:00',
                        'thursday' => '10:00-23:00',
                        'friday' => '10:00-23:00',
                        'saturday' => '10:00-23:00',
                        'sunday' => '10:00-23:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats'],
                ],
            ],
            [
                'name' => 'Zahir Kebab',
                'logo' => 'ZahirKebab.png',
                'address' => 'Kolejowa 3, 59-222 Legnica',
                'latitude' => 51.212331626618635,
                'longitude' => 16.168663992759292,
                'year_opened' => 2019,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:00-00:00',
                        'tuesday' => '11:00-00:00',
                        'wednesday' => '11:00-00:00',
                        'thursday' => '11:00-00:00',
                        'friday' => '11:00-02:00',
                        'saturday' => '11:00-02:00',
                        'sunday' => '11:00-00:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats'],
                ],
            ],
            [
                'name' => 'Cyrus Kebab',
                'logo' => 'Cyrus Kebab.png',
                'address' => 'ul. Rynek 20, Legnica',
                'latitude' => 51.20789180976535,
                'longitude' => 16.161067304224307,
                'year_opened' => 2010,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-22:00',
                        'tuesday' => '10:00-22:00',
                        'wednesday' => '10:00-22:00',
                        'thursday' => '10:00-22:00',
                        'friday' => '10:00-00:00',
                        'saturday' => '10:00-00:00',
                        'sunday' => '10:00-22:00',
                    ],
                    'meat_types' => ['beef', 'chicken', 'falafel'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats', 'phone'],
                ],
            ],
            [
                'name' => 'Leo Kebab',
                'logo' => 'LeoKebab.png',
                'address' => 'Jaworzyńska 4, 59-220 Legnica',
                'latitude' => 51.204396531055814,
                'longitude' => 16.15991388505192,
                'year_opened' => 2024,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-00:00',
                        'tuesday' => '10:00-00:00',
                        'wednesday' => '10:00-00:00',
                        'thursday' => '10:00-00:00',
                        'friday' => '10:00-00:00',
                        'saturday' => '10:00-00:00',
                        'sunday' => '10:00-00:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'delivery', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats', 'website', 'app'],
                ],
            ],
            [
                'name' => 'Piri Piri Kebab',
                'logo' => 'PiriPiri.png',
                'address' => 'Szkolna 1, 59-220 Legnica',
                'latitude' => 51.204145748458735,
                'longitude' => 16.160656410287114,
                'year_opened' => 2024,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:00-22:00',
                        'tuesday' => '11:00-22:00',
                        'wednesday' => '11:00-22:00',
                        'thursday' => '11:00-22:00',
                        'friday' => '11:00-23:00',
                        'saturday' => '11:00-23:00',
                        'sunday' => '12:00-23:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'GLOVO', 'Pyszne.pl', 'UberEats'],
                ],
            ],
            [
                'name' => 'LaraDöner Kebab',
                'logo' => 'LaraDoner.png',
                'address' => 'Wrocławska 13, 59-220 Legnica',
                'latitude' => 51.20957541173985,
                'longitude' => 16.167800192775434,
                'year_opened' => 2018,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-22:00',
                        'tuesday' => '10:00-22:00',
                        'wednesday' => '10:00-22:00',
                        'thursday' => '10:00-22:00',
                        'friday' => '10:00-22:00',
                        'saturday' => '10:00-22:00',
                        'sunday' => '12:00-22:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'GLOVO'],
                ],
            ],
            [
                'name' => 'MIX Kebab',
                'logo' => 'MIXkebab.png',
                'address' => 'Wrocławska 23a, 59-220 Legnica',
                'latitude' => 51.20922838725052,
                'longitude' => 16.16930333165232,
                'year_opened' => 2014,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:00-21:00',
                        'tuesday' => '11:00-21:00',
                        'wednesday' => '11:00-21:00',
                        'thursday' => '11:00-21:00',
                        'friday' => '11:00-21:00',
                        'saturday' => '12:00-21:00',
                        'sunday' => '12:00-21:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery','Pyszne.pl',],
                ],
            ],
            [
                'name' => 'Stambul Kebab',
                'logo' => 'Stambulkebab.png',
                'address' => 'Chojnowska 21A, 59-220 Legnica',
                'latitude' => 51.207180695943826,
                'longitude' => 16.156981015984435,
                'year_opened' => 2015,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:00-23:00',
                        'tuesday' => '11:00-23:00',
                        'wednesday' => '11:00-23:00',
                        'thursday' => '11:00-23:00',
                        'friday' => '11:00-01:00',
                        'saturday' => '11:00-01:00',
                        'sunday' => '12:00-23:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery','Pyszne.pl','GLOVO'],
                ],
            ],
            [
                'name' => 'MAXI Kebab',
                'logo' => 'MAXIkebab.png',
                'address' => 'parking Carrefour, aleja Piłsudskiego 84, 59-220 Legnica',
                'latitude' => 51.201107506422694,
                'longitude' => 16.214771841100685,
                'year_opened' => 2016,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '11:30-20:00',
                        'tuesday' => '11:30-20:00',
                        'wednesday' => '11:30-20:00',
                        'thursday' => '11:30-20:00',
                        'friday' => '11:30-20:00',
                        'saturday' => '11:00-20:00',
                        'sunday' => 'closed',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => true,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway'],
                ],
            ],
            [
                'name' => 'AM AM Kebab',
                'logo' => 'AMAMkebab.png',
                'address' => 'Wrocławska 155, 59-220 Legnica',
                'latitude' => 51.20953053230241,
                'longitude' => 16.187050632497762,
                'year_opened' => 2023,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-20:00',
                        'tuesday' => '10:00-20:00',
                        'wednesday' => '10:00-20:00',
                        'thursday' => '10:00-20:00',
                        'friday' => '10:00-20:00',
                        'saturday' => '10:00-20:00',
                        'sunday' => '11:00-20:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery','Pyszne.pl','GLOVO'],
                ],
            ],
            [
                'name' => 'King House Kebab',
                'logo' => 'KingHousekebab.png',
                'address' => 'aleja Piłsudskiego 38, 59-220 Legnica',
                'latitude' => 51.2046275625518,
                'longitude' => 16.188553452344834,
                'year_opened' => 2021,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => 'closed',
                        'tuesday' => '12:00-21:30',
                        'wednesday' => '12:00-21:30',
                        'thursday' => '12:00-21:30',
                        'friday' => '12:00-22:00',
                        'saturday' => '12:00-22:00',
                        'sunday' => '12:00-21:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery','Pyszne.pl','GLOVO'],
                ],
            ],
            [
                'name' => 'Kavovarka kebab kraft',
                'logo' => 'Kavovarkakebab.png',
                'address' => 'Górnicza 10B, 59-220 Legnica',
                'latitude' => 51.205534119307664,
                'longitude' => 16.186554399764407,
                'year_opened' => 2019,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '12:00-21:00',
                        'tuesday' => '12:00-21:00',
                        'wednesday' => '12:00-21:00',
                        'thursday' => '12:00-21:00',
                        'friday' => '12:00-21:00',
                        'saturday' => '12:00-21:00',
                        'sunday' => 'closed',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => true,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery', 'GLOVO'],
                ],
            ],
            [
                'name' => 'Hallo Kebap',
                'logo' => 'Hallokebap.png',
                'address' => 'Stefana Czarnieckiego 19c, 59-220 Legnica',
                'latitude' => 51.21170635321223,
                'longitude' => 16.17522528962012,
                'year_opened' => 2024,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => 'closed',
                        'tuesday' => '12:00-20:00',
                        'wednesday' => '12:00-20:00',
                        'thursday' => '12:00-20:00',
                        'friday' => '12:00-21:00',
                        'saturday' => '12:00-21:00',
                        'sunday' => '12:00-21:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway'],
                ],
            ],
            [
                'name' => 'Kebab&Gyros',
                'logo' => 'KebabGyros.png',
                'address' => 'Roberta Schumana 17, 59-220 Legnica',
                'latitude' => 51.18545694515532,
                'longitude' => 16.17237339999809,
                'year_opened' => 2018,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-20:00',
                        'tuesday' => '10:00-20:00',
                        'wednesday' => '10:00-20:00',
                        'thursday' => '10:00-20:00',
                        'friday' => '10:00-20:00',
                        'saturday' => '10:00-20:00',
                        'sunday' => 'closed',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => true,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery', 'GLOVO', 'Pyszne.pl'],
                ],
            ],
            [
                'name' => 'KEBAB TRUCK',
                'logo' => 'KEBABTRUCK.png',
                'address' => 'Iwaszkiewicza 1, 59-220 Legnica',
                'latitude' => 51.20793517150324,
                'longitude' => 16.213413324430963,
                'year_opened' => 2021,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00-19:00',
                        'tuesday' => '10:00-19:00',
                        'wednesday' => '10:00-19:00',
                        'thursday' => '10:00-19:00',
                        'friday' => '10:00-19:00',
                        'saturday' => '10:00-19:00',
                        'sunday' => 'closed',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => false,
                    'is_in_stall' => true,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'Pyszne.pl'],
                ],
            ],
            [
                'name' => 'Had Food - Pizza Kebab Burger',
                'logo' => 'HadFood.png',
                'address' => 'Fabryczna 13, 59-220 Legnica',
                'latitude' => 51.20678398261018,
                'longitude' => 16.178698811654844,
                'year_opened' => 2023,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '12:00–22:00',
                        'tuesday' => '12:00–22:00',
                        'wednesday' => '12:00–22:00',
                        'thursday' => '12:00–22:00',
                        'friday' => '12:00–23:00',
                        'saturday' => '12:00–23:00',
                        'sunday' => '12:00–21:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => true,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery','Pyszne.pl', 'GLOVO'],
                ],
            ],
            [
                'name' => 'Bejrut Restauracja Libańska',
                'logo' => 'Bejrut.png',
                'address' => 'aleja Piłsudskiego 18, 59-220 Legnica',
                'latitude' => 51.205150802472936,
                'longitude' => 16.18535164110259,
                'year_opened' => 2023,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => '10:00–00:00',
                        'tuesday' => '10:00–00:00',
                        'wednesday' => '10:00–00:00',
                        'thursday' => '12:00–22:00',
                        'friday' => '10:00–02:00',
                        'saturday' => '10:00–02:00',
                        'sunday' => '10:00–00:00',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'OPEN',
                    'is_craft' => true,
                    'is_in_stall' => false,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery'],
                ],
            ],
            [
                'name' => 'Rulo Kebab',
                'logo' => 'Rulokebab.png',
                'address' => 'Nowy Świat, 59-220 Legnica',
                'latitude' => 51.20514161487065,
                'longitude' => 16.154530893252073,
                'year_opened' => 2023,
                'year_closed' => null,
                'details' => [
                    'opening_hours' => [
                        'monday' => 'closed',
                        'tuesday' => 'closed',
                        'wednesday' => 'closed',
                        'thursday' => 'closed',
                        'friday' => 'closed',
                        'saturday' => 'closed',
                        'sunday' => 'closed',
                    ],
                    'meat_types' => ['beef', 'chicken'],
                    'sauces' => ['mild', 'spicy', 'mixed', 'garlic', 'ketchup'],
                    'status' => 'CLOSED temporarily',
                    'is_craft' => false,
                    'is_in_stall' => false,
                    'is_chain_member' => false,
                    'ordering_options' => ['on-site', 'takeaway', 'delivery'],
                ],
            ],
        ];

        foreach ($kebabs as $kebab) {

            $kebabId = DB::table('kebab')->insertGetId([
                'name' => $kebab['name'],
                'logo' => $kebab['logo'],
                'address' => $kebab['address'],
                'latitude' => $kebab['latitude'],
                'longitude' => $kebab['longitude'],
                'year_opened' => $kebab['year_opened'],
                'year_closed' => $kebab['year_closed'],
            ]);

            DB::table('kebab_details')->insert([
                'kebab_id' => $kebabId,
                'opening_hours' => json_encode($kebab['details']['opening_hours']),
                'meat_types' => json_encode($kebab['details']['meat_types']),
                'sauces' => json_encode($kebab['details']['sauces']),
                'status' => $kebab['details']['status'],
                'is_craft' => $kebab['details']['is_craft'],
                'is_in_stall' => $kebab['details']['is_in_stall'],
                'is_chain_member' => $kebab['details']['is_chain_member'],
                'ordering_options' => json_encode($kebab['details']['ordering_options']),
            ]);
        }
    }
}
